[project]
name = "audio-separator-cli-node"
version = "0.1.0"
description = "Wraps around audio-separator command-line tool to generate stems with full control of parameters and ports."
readme = "README.md"
license = { file = "LICENSE" }

[project.urls]
Repository = "https://github.com/50J0uRNeR/comfyui-audio-separator-cli-node.git"

[tool.comfy]
PublisherId = "ericnathenback"
DisplayName = "audio-separator-cli-node"
